name: CI PLD Compilateur

on:
  push:
    branches: [ master, CI-Actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      working-directory: ./compiler
      run: make
  test: 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: make
      working-directory: ./compiler
      run: make
    - name: Execute python test script
      working-directory: ./tests
      continue-on-error: true
      run: python ifcc-test.py testfiles